-- ============================================
-- RELACIONAR ÁREAS COM CONTAMINANTES
-- ============================================

-- AUTO POSTO DE COLORES (NIS 51)
INSERT INTO AREA_CONTAMINADA_CONTAMINANTE (id_area, id_contaminante)
SELECT a.id, c.id FROM AREA_CONTAMINADA a, CONTAMINANTE c
WHERE a.nis = 51 AND c.nome IN ('COMBUSTÍVEIS AUTOMOTIVOS', 'SOLVENTES AROMÁTICOS', 'PAHs');

-- RHODIA (NIS 363)
INSERT INTO AREA_CONTAMINADA_CONTAMINANTE (id_area, id_contaminante)
SELECT a.id, c.id FROM AREA_CONTAMINADA a, CONTAMINANTE c
WHERE a.nis = 363 AND c.nome IN ('POPs', 'SOLVENTES HALOGENADOS', 'FENÓIS', 'BIOCIDAS');

-- RHODIA KM 69 (NIS 367)
INSERT INTO AREA_CONTAMINADA_CONTAMINANTE (id_area, id_contaminante)
SELECT a.id, c.id FROM AREA_CONTAMINADA a, CONTAMINANTE c
WHERE a.nis = 367 AND c.nome IN ('SOLVENTES HALOGENADOS', 'FENÓIS', 'BIOCIDAS', 'POPs');

-- BEQUISA (NIS 916)
INSERT INTO AREA_CONTAMINADA_CONTAMINANTE (id_area, id_contaminante)
SELECT a.id, c.id FROM AREA_CONTAMINADA a, CONTAMINANTE c
WHERE a.nis = 916 AND c.nome IN ('METAIS', 'SOLVENTES HALOGENADOS');

-- AUTO POSTO MONUMENTO (NIS 1009)
INSERT INTO AREA_CONTAMINADA_CONTAMINANTE (id_area, id_contaminante)
SELECT a.id, c.id FROM AREA_CONTAMINADA a, CONTAMINANTE c
WHERE a.nis = 1009 AND c.nome IN ('COMBUSTÍVEIS AUTOMOTIVOS', 'SOLVENTES AROMÁTICOS');

-- JOÃO GONÇALVES (NIS 1282)
INSERT INTO AREA_CONTAMINADA_CONTAMINANTE (id_area, id_contaminante)
SELECT a.id, c.id FROM AREA_CONTAMINADA a, CONTAMINANTE c
WHERE a.nis = 1282 AND c.nome IN ('COMBUSTÍVEIS AUTOMOTIVOS', 'SOLVENTES AROMÁTICOS');

-- VIAÇÃO NORMANDY (NIS 1304)
INSERT INTO AREA_CONTAMINADA_CONTAMINANTE (id_area, id_contaminante)
SELECT a.id, c.id FROM AREA_CONTAMINADA a, CONTAMINANTE c
WHERE a.nis = 1304 AND c.nome IN ('Grupo TPH', 'SOLVENTES AROMÁTICOS', 'PAHs', 'COMBUSTÍVEIS AUTOMOTIVOS');

-- AUTO POSTO FORTALEZA (NIS 1710)
INSERT INTO AREA_CONTAMINADA_CONTAMINANTE (id_area, id_contaminante)
SELECT a.id, c.id FROM AREA_CONTAMINADA a, CONTAMINANTE c
WHERE a.nis = 1710 AND c.nome IN ('COMBUSTÍVEIS AUTOMOTIVOS', 'SOLVENTES AROMÁTICOS');

-- SAINT-GOBAIN (NIS 1766)
INSERT INTO AREA_CONTAMINADA_CONTAMINANTE (id_area, id_contaminante)
SELECT a.id, c.id FROM AREA_CONTAMINADA a, CONTAMINANTE c
WHERE a.nis = 1766 AND c.nome IN ('METAIS', 'SOLVENTES HALOGENADOS', 'PAHs');

-- MUNICÍPIO DE SÃO VICENTE (NIS 2019) - ACRi
INSERT INTO AREA_CONTAMINADA_CONTAMINANTE (id_area, id_contaminante)
SELECT a.id, c.id FROM AREA_CONTAMINADA a, CONTAMINANTE c
WHERE a.nis = 2019 AND c.nome IN ('OUTROS INORGÂNICOS');

-- RHODIA QUARENTENARIO (NIS 2567)
INSERT INTO AREA_CONTAMINADA_CONTAMINANTE (id_area, id_contaminante)
SELECT a.id, c.id FROM AREA_CONTAMINADA a, CONTAMINANTE c
WHERE a.nis = 2567 AND c.nome IN ('FENÓIS', 'BIOCIDAS', 'POPs', 'SOLVENTES HALOGENADOS');

-- AUTO POSTO AVALANCHE (NIS 3375)
INSERT INTO AREA_CONTAMINADA_CONTAMINANTE (id_area, id_contaminante)
SELECT a.id, c.id FROM AREA_CONTAMINADA a, CONTAMINANTE c
WHERE a.nis = 3375 AND c.nome IN ('COMBUSTÍVEIS AUTOMOTIVOS', 'PAHs');

-- COHAB SÍTIO BARRANCO (NIS 4170) - ACRi
INSERT INTO AREA_CONTAMINADA_CONTAMINANTE (id_area, id_contaminante)
SELECT a.id, c.id FROM AREA_CONTAMINADA a, CONTAMINANTE c
WHERE a.nis = 4170 AND c.nome IN ('METAIS', 'OUTROS INORGÂNICOS', 'BIOCIDAS', 'POPs');

-- UNIMETAL (NIS 4304)
INSERT INTO AREA_CONTAMINADA_CONTAMINANTE (id_area, id_contaminante)
SELECT a.id, c.id FROM AREA_CONTAMINADA a, CONTAMINANTE c
WHERE a.nis = 4304 AND c.nome IN ('METAIS', 'SOLVENTES HALOGENADOS', 'PAHs', 'METANO');